version: '3'
services:
  truffle:
    build:
      context: ./truffle@beta
      dockerfile: Dockerfile
    command: bash
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
      - "9545:9545"